name: Release Drafter

on:
  push:
    branches:
      - develop*
      - main*
  pull_request:
    # pull_request event is required only for autolabeler
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up from previous run
        run: sudo rm -rf "${GITHUB_WORKSPACE}/*"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: "1000"

      - name: Bump version and push tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GHE_TOKEN }}
          WITH_V: false
          VERBOSE: true
          DRY_RUN: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main, main-2.x
          PRERELEASE_SUFFIX: RC

      - name: Create a GitHub release
        uses: release-drafter/release-drafter@v5.21.1
        if: github.ref == 'refs/heads/develop'
        with:
          config-name: release_drafter.yml
          tag: ${{ steps.bump_version.outputs.new_tag }}
          name: Release ${{ steps.bump_version.outputs.new_tag }}
          version: ${{ steps.bump_version.outputs.new_tag }}
          publish: false
          commitish: develop
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GHE_TOKEN }}

      - name: Create a GitHub release
        uses: release-drafter/release-drafter@v5.21.1
        if: github.ref == 'refs/heads/main'
        with:
          config-name: release_drafter.yml
          tag: ${{ steps.bump_version.outputs.new_tag }}
          name: Release ${{ steps.bump_version.outputs.new_tag }}
          version: ${{ steps.bump_version.outputs.new_tag }}
          publish: true
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GHE_TOKEN }}
